# Generated by Django 5.2.7 on 2025-10-15 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(unique=True, verbose_name='페이지 번호')),
                ('question_text', models.CharField(max_length=200, verbose_name='질문 텍스트')),
                ('description', models.TextField(verbose_name='설명')),
                ('option_a_text', models.CharField(max_length=100, verbose_name='옵션 A 텍스트')),
                ('option_b_text', models.CharField(max_length=100, verbose_name='옵션 B 텍스트')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(max_length=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.question')),
            ],
        ),
    ]
